# Generated by Django 5.1.3 on 2024-11-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Untitled Book', max_length=255, verbose_name='Title'),
        ),
    ]
