# Generated by Django 5.1.3 on 2024-11-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_book_description_book_published_alter_book_discount_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
